language: cpp 
os:
  - linux
  - osx
complier:
  - gcc 
addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
script:
  - g++ -Wall -Wextra -Werror -I main.c file_creation.c form_sorter.c
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./demo ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --error-exitcode=1 --enable=warning,performance,information,style *.cpp *.h ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then g++ --version ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --version ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --version ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
