language: cpp 
os:
  - linux
  - osx
complier:
  - gcc 
  
addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - cmake
      - clang

script:
  - ctest --output-on-failure
  - cd "${TRAVIS_BUILD_DIR}"
  - cppcheck --std=c99 --enable=all -inconclusive src/*.c
  - cppcheck --std=c++11 --enable=all -inconclusive test/*.cpp
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWRAP_VALGRIND=ON .
  - make

after_success:
  - cd "${TRAVIS_BUILD_DIR}"
  - bash <(curl -s https://codecov.io/bash) -f "TP_Task1_C-/src/*"
